spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eTicar
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  application:
    name: eTicar
  jpa:
    hibernate:
      ddl-auto: update